# Generated by Django 2.2.5 on 2019-09-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('User_lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('User_lon', models.DecimalField(decimal_places=10, max_digits=13)),
                ('POI_NAME', models.CharField(max_length=255, null=True)),
                ('ST_NAME', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
