# Generated by Django 2.2.5 on 2019-09-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pune_POI',
            fields=[
                ('POI_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('LINK_ID', models.BigIntegerField()),
                ('TYPE', models.CharField(max_length=255)),
                ('POI_NAME', models.CharField(max_length=255)),
                ('ST_NAME', models.CharField(max_length=255)),
                ('Lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('Lon', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
    ]
