# Generated by Django 2.2.5 on 2019-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pune_poi',
            name='LINK_ID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pune_poi',
            name='Lat',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='pune_poi',
            name='Lon',
            field=models.DecimalField(decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='pune_poi',
            name='POI_NAME',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pune_poi',
            name='ST_NAME',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pune_poi',
            name='TYPE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
