# Generated by Django 2.2.5 on 2019-09-18 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190918_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pune_poi',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
